## 利用GitHub Actions每天定时给搜索引擎推送链接，提高收录率 ##
name: searchPush
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 17 * * *'


jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes 
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5
      - name: make
        run: make
      - name: baidu
        run: ./urls-random-generator -u https://www.ygang.top/ -c 10 -f urls-baidu.txt 
      - name: push to baidu
        run: curl -H 'Content-Type:text/plain' --data-binary @urls-baidu.txt "http://data.zz.baidu.com/urls?site=https://www.ygang.top&token=${{ secrets.BAIDU_TOKEN }}" \ 
      - name: clear urls-baidu.txt
        run: rm -rf urls-baidu.txt
